-- EG Gestor Vendas - SQL Server Script
-- Script para criação do banco de dados e tabelas no SQL Server (SQLEXPRESS)

-- Criação do Banco de Dados (opcional se já existir)
-- CREATE DATABASE BancoSqlServer;
-- GO

USE BancoSqlServer;
GO

-- 1) CADASTRO DE VENDEDORES
CREATE TABLE Vendedores (
    ID_VENDEDOR INT PRIMARY KEY IDENTITY(1,1),
    NOME_VENDEDOR NVARCHAR(150) NOT NULL,
    RECEBE_COMISSAO CHAR(1) CHECK (RECEBE_COMISSAO IN ('S', 'N')),
    COMISSAO DECIMAL(10, 2) DEFAULT 0
);

-- 2) CADASTRO DE CLIENTES
CREATE TABLE Clientes (
    ID_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
    STATUS NVARCHAR(10) CHECK (STATUS IN ('ATIVO', 'INATIVO')),
    NOME_CLIENTE NVARCHAR(150) NOT NULL,
    RUA NVARCHAR(255),
    NR NVARCHAR(20),
    CEP NVARCHAR(10),
    SETOR NVARCHAR(100),
    CIDADE NVARCHAR(100),
    UF CHAR(2),
    REFERENCIA NVARCHAR(255),
    TELEFONE NVARCHAR(20)
);

-- 4) CADASTRO DE ESTOQUE/LOCALIZAÇÃO (Tipo de Localização)
CREATE TABLE Localizacoes (
    ID_LOCALIZACAO INT PRIMARY KEY IDENTITY(1,1),
    TIPO_LOCALIZACAO NVARCHAR(50) NOT NULL -- 'INTERNO-FIXO' ou 'MÓVEL'
);

-- 6) CADASTRO DE FORNECEDORES
CREATE TABLE Fornecedores (
    ID_FORNECEDOR INT PRIMARY KEY IDENTITY(1,1),
    STATUS NVARCHAR(10) CHECK (STATUS IN ('ATIVO', 'INATIVO')),
    NOME_FORNECEDOR NVARCHAR(150) NOT NULL,
    RUA NVARCHAR(255),
    NR NVARCHAR(20),
    CEP NVARCHAR(10),
    SETOR NVARCHAR(100),
    CIDADE NVARCHAR(100),
    UF CHAR(2),
    REFERENCIA NVARCHAR(255),
    TELEFONE NVARCHAR(20)
);

-- 3) CADASTRO DE PRODUTOS
CREATE TABLE Produtos (
    ID_PRODUTO INT PRIMARY KEY IDENTITY(1,1),
    STATUS NVARCHAR(10) CHECK (STATUS IN ('ATIVO', 'INATIVO')),
    CODIGO NVARCHAR(50) UNIQUE,
    NOME_PRODUTO NVARCHAR(200) NOT NULL,
    QTD_ESTOQUE DECIMAL(18, 3) DEFAULT 0,
    UND NVARCHAR(10),
    PRECO_CUSTO DECIMAL(18, 2),
    MARGEM_LUCRO DECIMAL(10, 2),
    PRECO_VENDA DECIMAL(18, 2),
    CATEGORIA NVARCHAR(100),
    SUBCATEGORIA NVARCHAR(100),
    FABRICANTE NVARCHAR(100),
    ID_FORNECEDOR INT FOREIGN KEY REFERENCES Fornecedores(ID_FORNECEDOR),
    PESO_PADRAO DECIMAL(10, 3),
    LOCALIZACAO NVARCHAR(50), -- Link com local do estoque
    ESTOQUE_MINIMO DECIMAL(18, 3),
    ESTOQUE_MAXIMO DECIMAL(18, 3),
    NCM NVARCHAR(20),
    CTS NVARCHAR(10),
    CFOP NVARCHAR(10),
    ICMS DECIMAL(5, 2),
    IPI DECIMAL(5, 2),
    CODIGO_BARRAS NVARCHAR(100)
);

-- 5) CADASTRO TIPO DE PAGAMENTO
CREATE TABLE TiposPagamento (
    ID_TIPO INT PRIMARY KEY IDENTITY(1,1),
    TIPO_PGTO NVARCHAR(50) NOT NULL,
    PRODUTIVO CHAR(1) CHECK (PRODUTIVO IN ('S', 'N'))
);

-- 7) CADASTRO DE DESPESAS
CREATE TABLE Despesas (
    ID_DESPESA INT PRIMARY KEY IDENTITY(1,1),
    NOME_DESPESA NVARCHAR(150) NOT NULL,
    STATUS NVARCHAR(10) CHECK (STATUS IN ('ATIVO', 'INATIVO'))
);

-- 8) PEDIDOS (Cabeçalho)
CREATE TABLE Pedidos (
    ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
    DATA_PEDIDO DATETIME DEFAULT GETDATE(),
    NR_NOTA NVARCHAR(50),
    ID_FORNECEDOR INT FOREIGN KEY REFERENCES Fornecedores(ID_FORNECEDOR),
    TOTAL_PEDIDO DECIMAL(18, 2)
);

-- 8.1) PEDIDOS (Itens)
CREATE TABLE Pedido_Itens (
    ID_ITEM_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
    ID_PEDIDO INT FOREIGN KEY REFERENCES Pedidos(ID_PEDIDO),
    ID_PRODUTO INT FOREIGN KEY REFERENCES Produtos(ID_PRODUTO),
    ITEM_ATENDIDO CHAR(1) CHECK (ITEM_ATENDIDO IN ('S', 'N')),
    PRECO_CUSTO DECIMAL(18, 2),
    QUANTIDADE DECIMAL(18, 3),
    TOTAL_ITEM AS (PRECO_CUSTO * QUANTIDADE)
);

-- 9) VENDAS (Cabeçalho)
CREATE TABLE Vendas (
    ID_VENDA INT PRIMARY KEY IDENTITY(70000, 1), -- Sequence inicia em 70.000
    DATA_HORA DATETIME DEFAULT GETDATE(),
    ID_VENDEDOR INT FOREIGN KEY REFERENCES Vendedores(ID_VENDEDOR),
    ID_CLIENTE INT FOREIGN KEY REFERENCES Clientes(ID_CLIENTE),
    ID_TIPO_PGTO INT FOREIGN KEY REFERENCES TiposPagamento(ID_TIPO),
    TOTAL_VENDA DECIMAL(18, 2)
);

-- 9.1) VENDAS (Itens)
CREATE TABLE Venda_Itens (
    ID_ITEM_VENDA INT PRIMARY KEY IDENTITY(1,1),
    ID_VENDA INT FOREIGN KEY REFERENCES Vendas(ID_VENDA),
    ID_PRODUTO INT FOREIGN KEY REFERENCES Produtos(ID_PRODUTO),
    PRECO_VENDA DECIMAL(18, 2),
    QUANTIDADE DECIMAL(18, 3),
    DESCONTO_RS DECIMAL(18, 2) DEFAULT 0,
    DESCONTO_PERCENT DECIMAL(5, 2) DEFAULT 0,
    TOTAL_PRODUTO DECIMAL(18, 2)
);

-- 10) CAIXA
CREATE TABLE Caixa (
    ID_CAIXA INT PRIMARY KEY IDENTITY(1,1),
    DATA DATE DEFAULT CAST(GETDATE() AS DATE),
    ID_DESPESA INT FOREIGN KEY REFERENCES Despesas(ID_DESPESA),
    VALOR_DESPESA DECIMAL(18, 2),
    FECHAR_CAIXA CHAR(1) CHECK (FECHAR_CAIXA IN ('S', 'N'))
);

GO

-- TRIGGERS PARA MOVIMENTAÇÃO DE ESTOQUE --

-- Trigger para entrada de estoque via Pedido (quando item_atendido = 'S')
CREATE TRIGGER TRG_MovimentaEstoque_Pedido
ON Pedido_Itens
AFTER INSERT
AS
BEGIN
    UPDATE P
    SET P.QTD_ESTOQUE = P.QTD_ESTOQUE + I.QUANTIDADE
    FROM Produtos P
    JOIN inserted I ON P.ID_PRODUTO = I.ID_PRODUTO
    WHERE I.ITEM_ATENDIDO = 'S';
END;
GO

-- Trigger para saída de estoque via Venda
CREATE TRIGGER TRG_MovimentaEstoque_Venda
ON Venda_Itens
AFTER INSERT
AS
BEGIN
    UPDATE P
    SET P.QTD_ESTOQUE = P.QTD_ESTOQUE - I.QUANTIDADE
    FROM Produtos P
    JOIN inserted I ON P.ID_PRODUTO = I.ID_PRODUTO;
END;
GO
